id: I7C87C34E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T07:29:07+00:00'
last_modified: '2022-06-09T17:59:44.955071+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG010265
  title: གོམ་སྟབས་དང་ཞབས་རྗེས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    81D3:
      image_group_id: I1KG570
      title: ''
      total_pages: 378
      order: 1
      base_file: 81D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
