id: P000305
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG010265
  title: གོམ་སྟབས་དང་ཞབས་རྗེས་
  author: ''
  volumes:
    5288b1e3c5964f95a5613808ed310c2a:
      image_group_id: I1KG570
      title: ''
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
